Repository slid-todo/back, pull requests merged in 2024-12, with the labels that each got.

#21 목표, 할일 엔티티 생성
  src/main/java/com/codeit/todo/domain/Goal.java
  src/main/java/com/codeit/todo/domain/Todo.java
Labels: ⚡️ Simple

#22 feat : 스웨거 설정 및 할 일 전체 조회(무한 스크롤) 구현
  build.gradle
  src/main/java/com/codeit/todo/common/config/SwaggerConfig.java
  src/main/java/com/codeit/todo/domain/Todo.java
  src/main/java/com/codeit/todo/repository/GoalRepository.java
  src/main/java/com/codeit/todo/repository/TodoRepository.java
  src/main/java/com/codeit/todo/service/todo/TodoService.java
  src/main/java/com/codeit/todo/service/todo/impl/TodoServiceImpl.java
  src/main/java/com/codeit/todo/web/controller/TodoController.java
  src/main/java/com/codeit/todo/web/dto/request/auth/LoginRequest.java
  src/main/java/com/codeit/todo/web/dto/request/todo/ReadTodoRequest.java
  src/main/java/com/codeit/todo/web/dto/response/todo/ReadTodosResponse.java
Labels: 👀 리뷰가 필요해요

#24 feat : cors 설정
  src/main/java/com/codeit/todo/common/config/WebConfig.java
Labels: ⚡️ Simple

#25 docs : 운영 서버 스웨거 포트번호 추가
  src/main/java/com/codeit/todo/common/config/SwaggerConfig.java
Labels: ⚡️ Simple

#26 feat : 할일 등록 구현
  build.gradle
  src/main/java/com/codeit/todo/common/config/S3Config.java
  src/main/java/com/codeit/todo/common/exception/EntityNotFoundException.java
  src/main/java/com/codeit/todo/common/exception/payload/ErrorStatus.java
  src/main/java/com/codeit/todo/common/exception/user/UserNotFoundException.java
  src/main/java/com/codeit/todo/service/storage/StorageService.java
  src/main/java/com/codeit/todo/service/storage/impl/S3ServiceImpl.java
  src/main/java/com/codeit/todo/service/todo/TodoService.java
  src/main/java/com/codeit/todo/service/todo/impl/TodoServiceImpl.java
  src/main/java/com/codeit/todo/web/controller/TodoController.java
  src/main/java/com/codeit/todo/web/dto/request/todo/CreateTodoRequest.java
  src/main/java/com/codeit/todo/web/dto/response/todo/CreateTodoResponse.java
  src/main/resources/application-dev.yml
  src/test/resources/application.yml
Labels: 👀 리뷰가 필요해요

#32 fix : EntityNotFoundException 내 필드 타입을 int -> string으로 변경
  src/main/java/com/codeit/todo/common/exception/EntityNotFoundException.java
  src/main/java/com/codeit/todo/common/exception/user/UserNotFoundException.java
  src/main/java/com/codeit/todo/service/todo/impl/TodoServiceImpl.java
Labels: ⚡️ Simple

#27 feat: 로그인 구현
  build.gradle
  src/main/java/com/codeit/todo/common/config/JwtTokenProvider.java
  src/main/java/com/codeit/todo/common/config/SecurityConfig.java
  src/main/java/com/codeit/todo/common/exception/CustomAccessDeniedHandler.java
  src/main/java/com/codeit/todo/common/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/codeit/todo/common/handler/GlobalRestControllerAdvice.java
  src/main/java/com/codeit/todo/repository/CustomUserDetails.java
  src/main/java/com/codeit/todo/repository/UserRepository.java
  src/main/java/com/codeit/todo/service/CustomUserDetailService.java
  src/main/java/com/codeit/todo/service/user/UserService.java
  src/main/java/com/codeit/todo/service/user/impl/UserServiceImpl.java
  src/main/java/com/codeit/todo/web/controller/AuthController.java
  src/main/java/com/codeit/todo/web/dto/request/auth/LoginRequest.java
  src/main/java/com/codeit/todo/web/filter/JwtAuthenticationFilter.java
  src/main/resources/application-dev.yml
  src/test/resources/application.yml
Labels: 👀 리뷰가 필요해요

#33 fix : 배포 시, 필요한 환경변수 값 추가 설정
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#34 fix : 배포 시, 필요한 환경변수 값 추가 설정
  deploy.sh
Labels: ⚡️ Simple

#35 fix : 배포 시, 필요한 환경변수 값 추가 설정
  deploy.sh
Labels: ⚡️ Simple

#36 fix : 배포 시, 필요한 환경변수 값 추가 설정
  deploy.sh
Labels: ⚡️ Simple

#44 feat : 할일 생성 시, 날짜 수만큼 인증 및 노트 객체를 만드는 기능 추가
  src/main/java/com/codeit/todo/domain/Complete.java
  src/main/java/com/codeit/todo/repository/CompleteRepository.java
  src/main/java/com/codeit/todo/service/todo/impl/TodoServiceImpl.java
Labels: 👀 리뷰가 필요해요

#45 feat : 할일 전체 조회 시, 인증 및 노트로 등록한 값도 불러오는 기능 추가
  src/main/java/com/codeit/todo/repository/CompleteRepository.java
  src/main/java/com/codeit/todo/service/todo/impl/TodoServiceImpl.java
  src/main/java/com/codeit/todo/web/dto/response/complete/ReadCompleteResponse.java
  src/main/java/com/codeit/todo/web/dto/response/todo/ReadTodosResponse.java
Labels: 👀 리뷰가 필요해요

#47 feat: 목표 조회
  src/main/java/com/codeit/todo/common/exception/goal/GoalNotFoundException.java
  src/main/java/com/codeit/todo/service/goal/GoalService.java
  src/main/java/com/codeit/todo/service/goal/impl/GoalServiceImpl.java
  src/main/java/com/codeit/todo/web/controller/GoalController.java
  src/main/java/com/codeit/todo/web/dto/response/goal/ReadGoalsResponse.java
Labels: 👀 리뷰가 필요해요

#53 docs : cors 설정에 로컬 주소 추가
  src/main/java/com/codeit/todo/common/config/WebConfig.java
Labels: ⚡️ Simple

#50 feat: 목표 생성
  src/main/java/com/codeit/todo/domain/Goal.java
  src/main/java/com/codeit/todo/service/goal/GoalService.java
  src/main/java/com/codeit/todo/service/goal/impl/GoalServiceImpl.java
  src/main/java/com/codeit/todo/web/controller/GoalController.java
  src/main/java/com/codeit/todo/web/dto/request/goal/CreateGoalRequest.java
  src/main/java/com/codeit/todo/web/dto/response/goal/CreateGoalResponse.java
Labels: 👀 리뷰가 필요해요

#51 feat: 목표 수정
  src/main/java/com/codeit/todo/common/exception/goal/GoalNotFoundException.java
  src/main/java/com/codeit/todo/domain/Goal.java
  src/main/java/com/codeit/todo/service/goal/GoalService.java
  src/main/java/com/codeit/todo/service/goal/impl/GoalServiceImpl.java
  src/main/java/com/codeit/todo/web/controller/GoalController.java
  src/main/java/com/codeit/todo/web/dto/request/goal/UpdateGoalRequest.java
  src/main/java/com/codeit/todo/web/dto/response/goal/UpdateGoalResponse.java
Labels: 🖥️ 개발중

#52 feat: 목표 삭제
  src/main/java/com/codeit/todo/domain/Goal.java
  src/main/java/com/codeit/todo/domain/Todo.java
  src/main/java/com/codeit/todo/service/goal/GoalService.java
  src/main/java/com/codeit/todo/service/goal/impl/GoalServiceImpl.java
  src/main/java/com/codeit/todo/web/controller/GoalController.java
  src/main/java/com/codeit/todo/web/dto/response/goal/DeleteGoalResponse.java
Labels: 🖥️ 개발중

#59 fix:
  src/main/java/com/codeit/todo/common/config/JwtTokenProvider.java
  src/main/java/com/codeit/todo/web/controller/AuthController.java
  src/main/java/com/codeit/todo/web/filter/JwtAuthenticationFilter.java
Labels: 👀 리뷰가 필요해요

#61 feat: 회원가입
  src/main/java/com/codeit/todo/common/config/JwtTokenProvider.java
  src/main/java/com/codeit/todo/common/config/PasswordEncoderConfig.java
  src/main/java/com/codeit/todo/common/config/SecurityConfig.java
  src/main/java/com/codeit/todo/common/exception/user/SignUpException.java
  src/main/java/com/codeit/todo/domain/User.java
  src/main/java/com/codeit/todo/service/user/UserService.java
  src/main/java/com/codeit/todo/service/user/impl/UserServiceImpl.java
  src/main/java/com/codeit/todo/web/controller/AuthController.java
  src/main/java/com/codeit/todo/web/dto/request/auth/SignUpRequest.java
  src/main/java/com/codeit/todo/web/dto/response/auth/SignUpResponse.java
  src/main/java/com/codeit/todo/web/filter/JwtAuthenticationFilter.java
Labels: 👀 리뷰가 필요해요

#62 fix : https 설정이 안되어있어, secure 설정을 false로 변경
  src/main/java/com/codeit/todo/common/config/JwtTokenProvider.java
Labels: ⚡️ Simple

#63 fix : 브라우저의 preflight 요청을 받지 못해 CORS 에러 발생하는 부분 수정
  src/main/java/com/codeit/todo/common/config/WebConfig.java
Labels: ⚡️ Simple

#65 fix : 로그 레벨을 debug까지 보는 것으로 수정
  src/main/resources/application-dev.yml
Labels: ⚡️ Simple

#66 fix : 토큰이 정상적으로 동작하는지 확인을 위해 로그 추가
  src/main/java/com/codeit/todo/web/filter/JwtAuthenticationFilter.java
Labels: ⚡️ Simple

#68 fix : 리액트 토큰 테스트를 위한 httpOnly 속성 비활성화
  src/main/java/com/codeit/todo/common/config/JwtTokenProvider.java
Labels: ⚡️ Simple

#69 fix : samesite 설정을 위한 set-cookie 헤더 추가
  src/main/java/com/codeit/todo/web/controller/AuthController.java
Labels: ⚡️ Simple

#71 fix : 쿠키 추가 설정
  src/main/java/com/codeit/todo/web/controller/AuthController.java
Labels: ⚡️ Simple

#81 feat : 오늘 할 일 진행상황 조회하는 API 생성
  src/main/java/com/codeit/todo/domain/Complete.java
  src/main/java/com/codeit/todo/repository/TodoRepository.java
  src/main/java/com/codeit/todo/service/todo/TodoService.java
  src/main/java/com/codeit/todo/service/todo/impl/TodoServiceImpl.java
  src/main/java/com/codeit/todo/web/controller/TodoController.java
  src/main/java/com/codeit/todo/web/dto/response/todo/ReadTodoProgressResponse.java
Labels: 👀 리뷰가 필요해요

#89 docs : 사용하지 않는 주석 제거
  src/main/java/com/codeit/todo/service/todo/impl/TodoServiceImpl.java
Labels: ⚡️ Simple

#92 feat : 최근 등록한 할 일에서 목표 제목도 가져오도록 수정
  src/main/java/com/codeit/todo/web/controller/TodoController.java
  src/main/java/com/codeit/todo/web/dto/response/todo/ReadTodosResponse.java
Labels: ⚡️ Simple

#94 feat : 최근 등록한 할 일, 목표별 할 일에서 목표 색상도 가져오도록 수정
  src/main/java/com/codeit/todo/service/todo/impl/TodoServiceImpl.java
  src/main/java/com/codeit/todo/web/dto/response/todo/ReadTodosResponse.java
  src/main/java/com/codeit/todo/web/dto/response/todo/ReadTodosWithGoalsResponse.java
Labels: 👀 리뷰가 필요해요

#97 feat : cors 경로 추가
  src/main/java/com/codeit/todo/common/config/CorsConfig.java
Labels: ⚡️ Simple

#101 feat: 쿠키에 도메인 추가
  src/main/java/com/codeit/todo/web/controller/AuthController.java
Labels: ⚡️ Simple

#107 refactor : 오늘 할일 응답 필드 추가/ 조회 시, 시작날짜와 끝날짜 사이에 있는 할일을 찾아오도록 개선
  src/main/java/com/codeit/todo/repository/TodoRepository.java
  src/main/java/com/codeit/todo/service/todo/impl/TodoServiceImpl.java
  src/main/java/com/codeit/todo/web/dto/response/todo/ReadTodayTodoResponse.java
Labels: ⚡️ Simple

#108 fix: 토큰을 다시 응답 헤더에 넣기, 토큰 유효시간 연장
  src/main/java/com/codeit/todo/common/config/JwtTokenProvider.java
  src/main/java/com/codeit/todo/web/controller/AuthController.java
Labels: ⚡️ Simple

#114 feat: 유저의 프로필 사진 변경 API
  src/main/java/com/codeit/todo/domain/User.java
  src/main/java/com/codeit/todo/service/user/UserService.java
  src/main/java/com/codeit/todo/service/user/impl/UserServiceImpl.java
  src/main/java/com/codeit/todo/web/controller/AuthController.java
  src/main/java/com/codeit/todo/web/dto/request/auth/UpdatePictureRequest.java
  src/main/java/com/codeit/todo/web/dto/response/auth/UpdatePictureResponse.java
Labels: 👀 리뷰가 필요해요

#116 feat : 목표별 할일 조회 시, 목표 기반으로 무한스크롤 하도록 변경
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  src/main/java/com/codeit/todo/repository/GoalRepository.java
  src/main/java/com/codeit/todo/repository/TodoRepository.java
  src/main/java/com/codeit/todo/service/todo/TodoService.java
  src/main/java/com/codeit/todo/service/todo/impl/TodoServiceImpl.java
  src/main/java/com/codeit/todo/web/controller/TodoController.java
  src/main/java/com/codeit/todo/web/dto/request/todo/ReadDashBoardTodoWithGoalRequest.java
  src/main/java/com/codeit/todo/web/dto/response/todo/ReadTodosWithGoalsResponse.java
Labels: 👀 리뷰가 필요해요

#122 feat: 종료된 할일 포함해 모든 목표, 할일, 인증 가져오기
  src/main/java/com/codeit/todo/repository/TodoRepository.java
  src/main/java/com/codeit/todo/service/goal/GoalService.java
  src/main/java/com/codeit/todo/service/goal/impl/GoalServiceImpl.java
  src/main/java/com/codeit/todo/service/todo/TodoService.java
  src/main/java/com/codeit/todo/service/todo/impl/TodoServiceImpl.java
  src/main/java/com/codeit/todo/service/user/impl/UserServiceImpl.java
  src/main/java/com/codeit/todo/web/controller/AuthController.java
  src/main/java/com/codeit/todo/web/controller/GoalController.java
  src/main/java/com/codeit/todo/web/controller/TodoController.java
  src/main/java/com/codeit/todo/web/dto/request/todo/ReadTodoCompleteWithGoalRequest.java
Labels: 📝 논의 필요

#123 refactor : 목표별 할일 조회 시, 기간이 안지난 할일을 조회하도록 개선
  src/main/java/com/codeit/todo/repository/GoalRepository.java
  src/main/java/com/codeit/todo/service/goal/impl/GoalServiceImpl.java
  src/main/java/com/codeit/todo/service/todo/impl/TodoServiceImpl.java
Labels: 👀 리뷰가 필요해요

#131 fix : 쿼리문 내 비교연산자 수정 및 CustomSlice 추가
  src/main/java/com/codeit/todo/repository/GoalRepository.java
  src/main/java/com/codeit/todo/service/todo/impl/TodoServiceImpl.java
  src/main/java/com/codeit/todo/web/dto/response/slice/CustomSlice.java
  src/main/java/com/codeit/todo/web/dto/response/todo/ReadTodosWithGoalsResponse.java
Labels: ⚡️ Simple

#134 feat: 타인 프로필 페이지 구현
  src/main/java/com/codeit/todo/repository/FollowRepository.java
  src/main/java/com/codeit/todo/service/user/UserService.java
  src/main/java/com/codeit/todo/service/user/impl/UserServiceImpl.java
  src/main/java/com/codeit/todo/web/controller/AuthController.java
  src/main/java/com/codeit/todo/web/dto/response/auth/ReadTargetUserResponse.java
  src/main/java/com/codeit/todo/web/dto/response/complete/ReadTargetUserCompleteResponse.java
Labels: 👀 리뷰가 필요해요

#137 fix: 검색 필드, 검색어를 파라미터에 추가, 토큰 요청 보내도록 수정
  src/main/java/com/codeit/todo/common/config/SecurityConfig.java
  src/main/java/com/codeit/todo/service/search/SearchService.java
  src/main/java/com/codeit/todo/service/search/impl/SearchServiceImpl.java
  src/main/java/com/codeit/todo/web/controller/SearchController.java
  src/main/java/com/codeit/todo/web/filter/JwtAuthenticationFilter.java
Labels: 👀 리뷰가 필요해요

#142 feat: 댓글 생성, 수정, 삭제
  src/main/java/com/codeit/todo/common/exception/comment/CommentNotFoundException.java
  src/main/java/com/codeit/todo/domain/Comment.java
  src/main/java/com/codeit/todo/repository/CommentRepository.java
  src/main/java/com/codeit/todo/service/comment/CommentService.java
  src/main/java/com/codeit/todo/service/comment/impl/CommentServiceImpl.java
  src/main/java/com/codeit/todo/service/user/impl/UserServiceImpl.java
  src/main/java/com/codeit/todo/web/controller/CommentController.java
  src/main/java/com/codeit/todo/web/dto/request/comment/CreateCommentRequest.java
  src/main/java/com/codeit/todo/web/dto/request/comment/UpdateCommentRequest.java
  src/main/java/com/codeit/todo/web/dto/response/comment/CreateCommentResponse.java
  src/main/java/com/codeit/todo/web/dto/response/comment/DeleteCommentResponse.java
  src/main/java/com/codeit/todo/web/dto/response/comment/UpdateCommentResponse.java
Labels: 👀 리뷰가 필요해요

#144 fix : 인증 상세 보기 시, 해당 유저가 아닌 다른 사람의 인증도 볼 수 있도록 수정
  src/main/java/com/codeit/todo/service/complete/CompleteService.java
  src/main/java/com/codeit/todo/service/complete/impl/CompleteServiceImpl.java
  src/main/java/com/codeit/todo/web/controller/CompleteController.java
Labels: ⚡️ Simple

#145 feat : 팔로워가 최근 등록한 인증 목록 조회
  src/main/java/com/codeit/todo/repository/CompleteRepository.java
  src/main/java/com/codeit/todo/repository/FollowRepository.java
  src/main/java/com/codeit/todo/service/follow/FollowService.java
  src/main/java/com/codeit/todo/service/follow/impl/FollowServiceImpl.java
  src/main/java/com/codeit/todo/web/controller/FollowController.java
  src/main/java/com/codeit/todo/web/dto/request/follow/ReadFollowRequest.java
  src/main/java/com/codeit/todo/web/dto/response/follow/ReadFollowResponse.java
Labels: 👀 리뷰가 필요해요

#146 feat : 좋아요 추가, 삭제 구현
  src/main/java/com/codeit/todo/common/exception/likes/LikesNotFoundException.java
  src/main/java/com/codeit/todo/domain/Likes.java
  src/main/java/com/codeit/todo/repository/LikesRepository.java
  src/main/java/com/codeit/todo/service/likes/LikesService.java
  src/main/java/com/codeit/todo/service/likes/impl/LikesServiceImpl.java
  src/main/java/com/codeit/todo/web/controller/CompleteController.java
  src/main/java/com/codeit/todo/web/controller/LikesController.java
  src/main/java/com/codeit/todo/web/dto/response/likes/CreateLikeResponse.java
  src/main/java/com/codeit/todo/web/dto/response/likes/DeleteLikeResponse.java
Labels: 👀 리뷰가 필요해요

#154 fix: 팔로우 여부 찾아오는 쿼리 수정
  src/main/java/com/codeit/todo/repository/FollowRepository.java
  src/main/java/com/codeit/todo/service/follow/impl/FollowServiceImpl.java
Labels: 📝 논의 필요

#152 feat: 회원 탈퇴
  src/main/java/com/codeit/todo/common/config/JwtTokenProvider.java
  src/main/java/com/codeit/todo/domain/User.java
  src/main/java/com/codeit/todo/repository/CommentRepository.java
  src/main/java/com/codeit/todo/repository/FollowRepository.java
  src/main/java/com/codeit/todo/repository/GoalRepository.java
  src/main/java/com/codeit/todo/repository/LikesRepository.java
  src/main/java/com/codeit/todo/service/user/UserService.java
  src/main/java/com/codeit/todo/service/user/impl/UserServiceImpl.java
  src/main/java/com/codeit/todo/web/controller/AuthController.java
  src/main/java/com/codeit/todo/web/dto/request/auth/SignUpRequest.java
  src/main/java/com/codeit/todo/web/dto/response/auth/UpdateUserStatusResponse.java
  src/main/java/com/codeit/todo/web/filter/JwtAuthenticationFilter.java
Labels: 👀 리뷰가 필요해요

#157 fix : 오늘 할 일 진행상황 계산 오류 수정
  src/main/java/com/codeit/todo/service/todo/impl/TodoServiceImpl.java
Labels: 👀 리뷰가 필요해요

#162 feat : 인증 상세 보기 필드값 추가
  src/main/java/com/codeit/todo/web/dto/response/complete/ReadCompleteDetailResponse.java
Labels: ⚡️ Simple

#164 feat: 검색 페이지 응답에 필드 추가
  src/main/java/com/codeit/todo/web/dto/response/search/ReadSearchResponse.java
Labels: ⚡️ Simple

#166 fix: 검색어가 없을 때 예외처리
  src/main/java/com/codeit/todo/service/search/impl/SearchServiceImpl.java
Labels: ⚡️ Simple

#167 fix: 목표가 없을 때 빈 배열을 보내기
  src/main/java/com/codeit/todo/service/goal/impl/GoalServiceImpl.java
Labels: ⚡️ Simple

#168 fix: 팔로워, 팔로이 수 세는 쿼리 수정
  src/main/java/com/codeit/todo/repository/FollowRepository.java
Labels: ⚡️ Simple

#169 feat : 할일 상세 보기 필드값 추가
  src/main/java/com/codeit/todo/web/dto/response/todo/ReadTodoDetailResponse.java
Labels: ⚡️ Simple
